### ISSUE TITLE
[Bug] The naming of parameters is not uniform in InvocationRuntimes

### ISSUE THREAD

**Issue by Huijing-Xu** [reactivegroup/cloud-runtimes-jvm#24]
- [x] I have searched the [issues](https://github.com/reactivegroup/cloud-runtimes-jvm/issues) of this repository and believe that this is not a duplicate.

### Environment

* cloud-runtimes-jvm version: 1.0.2-SNAPSHOT
* branch: master

## Expected Behavior

The naming of parameters is uniform

## Actual Behavior

![image](https://user-images.githubusercontent.com/38981310/138452338-d183f0a0-8fcf-41a7-9300-61609f753361.png)

**Comment by kevinten10** [comment]
fix.
